version: '2'
services:
  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    env_file: '.env.mongodb'
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - ./app/api/:/usr/src/app/
      - /usr/src/node_modules
    links:
      - "mongodb"
    env_file:
      - ".env.mongodb"
      - ".env.api"
    command: /bin/bash -c "npm i && npm start"
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./app/client/:/usr/src/app/
      - /usr/src/node_modules
    links:
      - "api"
    command: /bin/bash -c "npm i && npm run build && npm start"